[project]
name = "template_denosing_algorithm"
version = "1.0.0"

[tool.compox]
algorithm_type = "Image2Image"
tags = ["image-denoising"]
description = "Denoises a sequence of images using the total variation denoising algorithm."
supported_devices = ["cpu", "gpu"]
default_device = "cpu"
additional_parameters = [
    {name = "denoising_weight", displayed_name = "Denoising weight", description = "The weight of the denoising term between 0 and 1. Higher values will result in more denoising, but can distort the image.", config = {type = "float_range", default = 0.1, min = 0.0, max = 1.0, step = 0.05, decimal_precision = 2, adjustable = true}},
]

# Whether to check if the module is importable by performing an import
# test.
check_importable = false

# Whether to obfuscate the .py files. The obfuscation
# is not implemented yet. For now, the .py files are minimized using
# python_minifier.
obfuscate = true
