[project]
name = "template_registration_algorithm"
version = "1.0.0"

[tool.compox]
algorithm_type = "Image2Alignment"
tags = ["image-alignment"]
description = "Performs a registration of a sequence of images."
supported_devices = ["cpu", "gpu"]
default_device = "cpu"
additional_parameters = [
    {name = "max_translation", displayed_name = "Max translation", description = "Maximum translation as a fraction of the image size.", config = {type = "float_range", default = 0.25, min = 0.0, max = 1.0, step = 0.05, decimal_precision = 2, adjustable = true}}
]
# Whether to check if the module is importable by performing an import
# test.
check_importable = false

# Whether to obfuscate the .py files. The obfuscation
# is not implemented yet. For now, the .py files are minimized using
# python_minifier.
obfuscate = true
